name: new_mini_casino
description: A new Flutter project.
publish_to: 'none'
version: 1.2.4+38
environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_flip_counter: ^0.2.5
  cupertino_icons: ^1.0.2
  supabase_flutter: ^1.10.23
#  cloud_firestore: ^4.4.5 
#  firebase_auth: ^4.2.2
#  firebase_core: ^2.8.0
#  firebase_storage: ^11.0.16
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.1.0
  http: ^0.13.4
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  auto_size_text: ^3.0.0
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.6.2
  syncfusion_flutter_sliders: ^21.2.3
  in_app_review: ^2.0.6
  pdfx: ^2.4.0
  in_app_update: ^4.0.1
  material_dialogs: ^1.1.4
  quickalert: ^1.0.1
  beamer: ^1.5.3
  lottie: ^2.3.2
  currency_text_input_formatter: ^2.1.9
  stack_appodeal_flutter: ^3.0.2
  flutter_gif: ^0.0.4
  gif: ^2.2.0
  shaky_animated_listview: ^0.0.5
  dropdown_button2: ^2.1.2
  freerasp: ^6.3.0
  blur: ^3.1.0
  platform_device_id: ^1.0.1
  get_ip_address: ^0.0.5
  flutter_native_splash: ^2.2.19
  yookassa_payments_flutter: ^1.2.2
  connectivity_plus: ^4.0.2
  webview_flutter: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  appmetrica_plugin: ^1.2.0
  ntp: ^2.0.0
  flutter_fortune_wheel: ^1.2.1
  modal_bottom_sheet: ^2.1.2
  badges: ^3.1.1
  circle_progress_bar: ^0.1.2
  flip_card: ^0.7.0
  flame: ^1.9.1
  flame_forge2d: ^0.15.0+1
  sentry_flutter: ^7.10.1
  pinput: ^3.0.1
  restart_app: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/other_images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/mines/
   - assets/images/
   - assets/blackjack/
   - assets/cars/
   - assets/houses/
   - assets/pins/
   - assets/stairs/
   - assets/animations/
   - assets/coinflip/
   - assets/games_logo/
   - assets/other_images/
