name: new_mini_casino
description: A new Flutter project.
publish_to: 'none'
version: 1.0.3+3

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  animated_flip_counter: ^0.2.5
  cloud_firestore: ^4.4.5
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.8.0
  firebase_storage: ^11.0.16
  flutterfire: ^0.0.1
  font_awesome_flutter: ^10.1.0
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.0.2
  http: ^0.13.4
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  auto_size_text: ^3.0.0
  provider: ^6.0.5
  flutter_staggered_grid_view: ^0.6.2
  syncfusion_flutter_sliders: ^20.4.53
  in_app_review: ^2.0.6
  pdfx: ^2.3.0
  in_app_update: ^4.0.1
  material_dialogs: ^1.1.4
  quickalert: ^1.0.1
  beamer: ^1.5.3
  lottie: ^2.3.2
  currency_text_input_formatter: ^2.1.9
  stack_appodeal_flutter: ^3.0.2
  flutter_gif: ^0.0.4
  gif: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true

  assets:
   - assets/
   - assets/mines/
   - assets/animations/
   - assets/coinflip/
   - assets/games_logo/
