import 'package:flutter/material.dart';
import 'package:new_mini_casino/business/store_manager.dart';

List<StoreItemModel> housesModels = [
  StoreItemModel(
    title: 'Sweet Home',
    price: 2500000,
    imageId: 0,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Brick House',
    price: 5170000,
    imageId: 1,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'American House',
    price: 3750000,
    imageId: 2,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Vacation Home',
    price: 14000000,
    imageId: 3,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Domed House',
    price: 25600000,
    imageId: 4,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Stavropol House',
    price: 33700000,
    imageId: 5,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Turkish Cottage',
    price: 38000000,
    imageId: 6,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Fairmont Vesper',
    price: 11515000,
    imageId: 7,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Elet House',
    price: 235000000,
    imageId: 8,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'High Tech House',
    price: 100300000,
    imageId: 9,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Hilton Dalaman',
    price: 305400000,
    imageId: 10,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Elegant House',
    price: 225725000,
    imageId: 11,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'The Weeknd House',
    price: 400380000,
    imageId: 12,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Mont Saint Michel',
    price: 725000000,
    imageId: 13,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Moscow City',
    price: 725000000,
    imageId: 14,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Marina Bay Sands',
    price: 555450000,
    imageId: 15,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Apple Park',
    price: 800500000,
    imageId: 16,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Villa Zhukovka',
    price: 86700000,
    imageId: 17,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Glass House',
    price: 100000000,
    imageId: 18,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Finnish House',
    price: 140800000,
    imageId: 19,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Romanian Parliament',
    price: 337400000000,
    imageId: 20,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Princess Tower',
    price: 218000000000,
    imageId: 21,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Bellagio Casino Hotel',
    price: 193000000000,
    imageId: 22,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'The White House',
    price: 72000000000,
    imageId: 23,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Glass House',
    price: 241000000,
    imageId: 24,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'House near St. Petersburg',
    price: 280000000,
    imageId: 25,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Desert House',
    price: 250000000,
    imageId: 26,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Villa on the lake',
    price: 170000000,
    imageId: 27,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Tropical House',
    price: 190000000,
    imageId: 28,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Villa in Spain',
    price: 380000000,
    imageId: 29,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Modern villa',
    price: 80000000,
    imageId: 30,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Modern House',
    price: 110000000,
    imageId: 31,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Chateau Erken castle',
    price: 13000000000,
    imageId: 32,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Gos Sovet MC',
    price: 31000000000,
    imageId: 33,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
];
