import 'package:flutter/material.dart';
import 'package:new_mini_casino/business/store_manager.dart';

List<StoreItemModel> housesModels = [
  StoreItemModel(
    title: 'Sweet home',
    price: 2500000,
    imageId: 0,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Brick house',
    price: 5170000,
    imageId: 1,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'American house',
    price: 3750000,
    imageId: 2,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Vacation home',
    price: 14000000,
    imageId: 3,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Domed house',
    price: 25600000,
    imageId: 4,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Stavropol house',
    price: 33700000,
    imageId: 5,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Turkish cottage',
    price: 38000000,
    imageId: 7,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Fairmont Vesper',
    price: 11515000,
    imageId: 6,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Elet house',
    price: 235000000,
    imageId: 8,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'High tech house',
    price: 100300000,
    imageId: 9,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Hilton Dalaman',
    price: 305400000,
    imageId: 10,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Elegant house',
    price: 225725000,
    imageId: 11,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'The Weeknd house',
    price: 400380000,
    imageId: 12,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Mont Saint Michel',
    price: 725000000,
    imageId: 13,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Moscow City',
    price: 725000000,
    imageId: 14,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Marina Bay Sands',
    price: 555450000,
    imageId: 15,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Apple Park',
    price: 800500000,
    imageId: 16,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Villa Zhukovka',
    price: 86700000,
    imageId: 17,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Glass house',
    price: 100000000,
    imageId: 18,
    color: Colors.blueGrey.shade100,
  ),
  StoreItemModel(
    title: 'Finnish house',
    price: 140800000,
    imageId: 19,
    premium: true,
    color: Colors.blueGrey.shade100,
  ),
];
