// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg_LHoovYO07-djRYSLHlpHZIDRFZ0zbc',
    appId: '1:242091631777:web:65c1c6c118b3b42e1b3ce0',
    messagingSenderId: '242091631777',
    projectId: 'mini-casino-8ee0f',
    authDomain: 'mini-casino-8ee0f.firebaseapp.com',
    storageBucket: 'mini-casino-8ee0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_BNNQbeIxnd2knl1V51i50oo1RHVFPc',
    appId: '1:242091631777:android:b2fefab7952fb5f51b3ce0',
    messagingSenderId: '242091631777',
    projectId: 'mini-casino-8ee0f',
    storageBucket: 'mini-casino-8ee0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbu_r80kaktHuKNuEz3mfvC-TIX63WEj0',
    appId: '1:242091631777:ios:7d0ee1e5dfd701d01b3ce0',
    messagingSenderId: '242091631777',
    projectId: 'mini-casino-8ee0f',
    storageBucket: 'mini-casino-8ee0f.appspot.com',
    iosClientId: '242091631777-movu6j6pk033mo8m6ac23i3ief18lsbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.newMiniCasino',
  );
}
